alcances:
    path:     /
    defaults: { _controller: "CespiIsoBundle:Alcances:index" }

alcances_show:
    path:     /{id}/show
    defaults: { _controller: "CespiIsoBundle:Alcances:show" }

alcances_new:
    path:     /new
    defaults: { _controller: "CespiIsoBundle:Alcances:new" }

alcances_create:
    path:     /create
    defaults: { _controller: "CespiIsoBundle:Alcances:create" }
    methods:  POST

alcances_edit:
    path:     /{id}/edit
    defaults: { _controller: "CespiIsoBundle:Alcances:edit" }

alcances_update:
    path:     /{id}/update
    defaults: { _controller: "CespiIsoBundle:Alcances:update" }
    methods:  [POST, PUT]

alcances_delete:
    path:     /{id}/delete
    defaults: { _controller: "CespiIsoBundle:Alcances:delete" }
    methods:  [POST, DELETE]
