Cespi\Bundle\IsoBundle\Entity\RegistroControlCambios:
    type: entity
    table: registro_control_cambios
    indexes:
        id_registro:
            columns:
                - id_registro
        id_usuario:
            columns:
                - user
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        revision:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        fecha:
            type: datetime
            nullable: true
            comment: ''
            default: CURRENT_TIMESTAMP
        motivo:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        updatedAt:
            type: datetime
            nullable: true
            comment: ''
            default: CURRENT_TIMESTAMP
            column: updated_at
        link:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''            
    manyToOne:
        idRegistro:
            targetEntity: Registro
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_registro:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Usuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
