Cespi\Bundle\IsoBundle\Entity\RegistroCargado:
    type: entity
    table: registro_cargado
    indexes:
        id_registro:
            columns:
                - id_registro
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: created_at
        user:
            type: integer
            nullable: false
            unsigned: false
            comment: ''            
    manyToOne:
        idRegistro:
            targetEntity: Registro
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_registro:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
