_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

cespi_iso:
    resource: "@CespiIsoBundle/Resources/config/routing.yml"
    prefix:   /
    schemes: [http]
