security:
    acl:
        connection: default
    encoders:
        Cespi\Bundle\IsoBundle\Entity\Usuarios: 
            algorithm : sha1
            encode_as_base64: false
            iterations: 1

            

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:

        user_db:
            entity:
                class: CespiIsoBundle:Usuarios
                property: username
                
    
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    
        main:
            anonymous: ~
            provider: user_db
            form_login:
                login_path: login
                check_path: login

           
    access_control:
          - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/saml/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/saml/metadata, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/documento, roles: [ROLE_USER, ROLE_ADMIN]}
          - { path: ^/usuario, roles: [ROLE_USER, ROLE_ADMIN] }
          - { path: ^/backend/usuarios, role: [ROLE_ADMIN]}
          - { path: ^/backend/estado, role: [ROLE_ADMIN]}          
          - { path: ^/backend, role: [ROLE_USER, ROLE_ADMIN]}
          
