<?php

namespace Cespi\Bundle\IsoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Cespi\Bundle\IsoBundle\Entity\RegistroCargadoDato;
/**
 * VMugUbicacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroCargadoDatoRepository extends EntityRepository
{
    
    
     /* SELECT *
FROM registro_cargado_dato r1
where created_at = (select max(created_at) from registro_cargado_dato r2 where r2.id_registro_cargado = r1.id_registro_cargado group by id_registro_cargado)
and r1.control_envio_email = true
*/      
    public function controlAviso()
    {
        $em = $this->getEntityManager();
        $q = $em->createQuery('SELECT r1 FROM Cespi\Bundle\IsoBundle\Entity\RegistroCargadoDato r1 '
                . ' WHERE r1.createdAt = (SELECT MAX(r2.createdAt) from Cespi\Bundle\IsoBundle\Entity\RegistroCargadoDato r2 where r2.idRegistroCargado = r1.idRegistroCargado group by r2.idRegistroCargado)'
                . ' and r1.control_envio_email = true ORDER BY r1.idRegistroCargado, r1.createdAt DESC');
        return $q->getResult();
    }
    
    
    public function getCamposAviso($res)
    { 
        $dato = date_format($res->getCreatedAt(),'Y-m-d H:i:s');
        $parameters = array('idreg'=> $res->getIdRegistroCargado()->getId(), 'created' => $dato);
        
        $em = $this->getEntityManager();
        $q = $em->createQuery('SELECT r1 FROM Cespi\Bundle\IsoBundle\Entity\RegistroCargadoDato r1 WHERE r1.idRegistroCargado  = :idreg and r1.createdAt = :created')->setParameters($parameters);
        
        return $q->getResult();
        
    }
}
